#!/bin/bash
if [ -z "$VPC_ID" ]
then
  echo VPC_ID is missing >&2
  exit 1
fi

if [ -z "$SUBNET_ID" ]
then
  echo SUBNET_ID is missing >&2
  exit 1
fi

export VPC_ID SUBNET_ID
packer build -machine-readable packer.json| tee packer.log
awk -F, '$0 ~/artifact,0,id/ {print $6}' packer.log | \
  sed -e 's/%!(PACKER_COMMA)/\n/g' | \
  sed -e 's/^/    /g' -e 's/:/: /g'
